### ISSUE TITLE
module dependency issue

### ISSUE THREAD

**Issue by rampageservices** [wgarunap/goconf#3]
hey man,

I'm working on edb again but have the following issue.
I'm on go v1.20

go: github.com/wgarunap/goconf@v0.5.0 requires
        gopkg.in/oleiade/reflections.v1@v1.0.0: go.mod has non-....v1 module path "github.com/oleiade/reflections" at revision v1.0.0

**Comment by rampageservices** [comment]
this seems to be the appropriate fix

https://github.com/wgarunap/goconf/pull/4

**Comment by wgarunap** [comment]
Thanks for upgrading the version. I have merged the PR.
